### ISSUE TITLE
Remediate High vulnerability

### ISSUE THREAD

**Issue by Lilalamar** [HumanCellAtlas/unity#25]
Snyk reports 1 [**High** vulnerability](https://app.snyk.io/org/humancellatlas/project/3298e72c-2500-48c7-9b85-8adda646d206) in HumanCellAtlas/unity nokogiri. Please remediate by the end of Q3 Milestone 3 or, if applicable, document as a false positive finding.

**Comment by Lilalamar** [comment]
From Jon: "The version of nokogiri installed is the latest available (1.10.4).  So there's also no remediation available for that if it isn't because of this [CVE](https://nvd.nist.gov/vuln/detail/CVE-2019-5477). The issue is that there aren't resolutions available for nokogiri." Note: a milestone has not been assigned to this ticket because it doesn't exist for this repo.

**Comment by bistline** [comment]
From Nokogiri: https://github.com/sparklemotion/nokogiri/issues/1582

The TL;DR is that the [XXE vulnerability in libxml2](https://nvd.nist.gov/vuln/detail/CVE-2016-9318) (upon which Nokogiri depends) is _only_ an issue for the gem if the application opts into accepting DTD loading and network access.  By default these are both false.  The stance of the maintainers is that this is not an issue for users of the gem that don't customize options.

There is still activity on their repo about this, so I'm going to leave it open for now, but this may get closed as a "false positive".

**Comment by bistline** [comment]
As per https://github.com/sparklemotion/nokogiri/issues/1582#issuecomment-537750186:

The maintainers of Nokogiri are asserting that this is a false positive as of v1.8.3.  The underlying issue was patched in libxml 2.9.8, which was pulled into Nokogiri in 1.8.3.  They specifically call out anyone who is a "security scanner" that this is already dealt with, and that it should be marked as green.

As a result, I'm closing this issue as we are on v1.10.4.
